CREATE TABLE [dbo].[Cars]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[MakeId] INT NOT NULL FOREIGN KEY REFERENCES CarMakers(Id),
	[Model] NVARCHAR(50) NOT NULL,
	[Year] INT NOT NULL,
	[Color] NVARCHAR(20) NOT NULL,
	[InStock] BIT NOT NULL,
	[Price] DECIMAL(18, 2) NOT NULL
)
