CREATE TABLE [dbo].[Reviews]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CarId] INT NOT NULL FOREIGN KEY REFERENCES Cars(Id),
	[Comment] NVARCHAR(500) NOT NULL,
	[Rating] INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE()
)
